// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4iE6Bwe5ite5NVXfhLNnR9XynWYdU6QM',
    appId: '1:884065563222:web:ef72d29d0533057cce01f7',
    messagingSenderId: '884065563222',
    projectId: 'citiguide-6db5c',
    authDomain: 'citiguide-6db5c.firebaseapp.com',
    storageBucket: 'citiguide-6db5c.firebasestorage.app',
    measurementId: 'G-3D1S8MEHP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDipH-WOvEVgEUeivMIt0BY-ITVSiE82Ak',
    appId: '1:884065563222:android:8b45adca27625ed3ce01f7',
    messagingSenderId: '884065563222',
    projectId: 'citiguide-6db5c',
    storageBucket: 'citiguide-6db5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWRTScby3RhFD-qc0-Yx3S0KlttuF2hBk',
    appId: '1:884065563222:ios:78c7ef2ac22a3e43ce01f7',
    messagingSenderId: '884065563222',
    projectId: 'citiguide-6db5c',
    storageBucket: 'citiguide-6db5c.firebasestorage.app',
    iosBundleId: 'com.example.cityguid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWRTScby3RhFD-qc0-Yx3S0KlttuF2hBk',
    appId: '1:884065563222:ios:78c7ef2ac22a3e43ce01f7',
    messagingSenderId: '884065563222',
    projectId: 'citiguide-6db5c',
    storageBucket: 'citiguide-6db5c.firebasestorage.app',
    iosBundleId: 'com.example.cityguid',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4iE6Bwe5ite5NVXfhLNnR9XynWYdU6QM',
    appId: '1:884065563222:web:357863ec4f5e12dfce01f7',
    messagingSenderId: '884065563222',
    projectId: 'citiguide-6db5c',
    authDomain: 'citiguide-6db5c.firebaseapp.com',
    storageBucket: 'citiguide-6db5c.firebasestorage.app',
    measurementId: 'G-5MNMFDJG0M',
  );
}
